name: build and run tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: boost
      run: sudo apt-get update && sudo apt-get install -yq libboost1.65-dev

    # build project
    - name: create build folder
      run: mkdir build
    - name: cmake
      working-directory: ./build/
      run: cmake .. -DCMAKE_BUILD_TYPE=Debug -G "Unix Makefiles"
    - name: make all
      run: make all

    # run tests
    - name: test
      working-directory: ./build/test/
      run: ./build/test/lab0_tst 